"""Compatibility exports from the validated deployment settings."""

from deployment_settings import AzureSettings, get_settings, load_environment


load_environment()
_settings = get_settings(AzureSettings)

SUBSCRIPTION_ID = _settings.AZURE_SUBSCRIPTION_ID
RESOURCE_GROUP = _settings.AZURE_RESOURCE_GROUP
SEARCH_SERVICE_NAME = _settings.AZURE_AI_SEARCH_SERVICE_NAME
SEARCH_ENDPOINT = _settings.AZURE_AI_SEARCH_ENDPOINT
SEARCH_CONNECTION_ID = _settings.AZURE_AI_SEARCH_CONNECTION_ID
API_VERSION = _settings.AZURE_AI_SEARCH_API_VERSION
PROJECT_ENDPOINT = _settings.AZURE_AI_PROJECT_ENDPOINT
FOUNDRY_ENDPOINT = _settings.AZURE_FOUNDRY_ENDPOINT
STORAGE_ACCOUNT = _settings.STORAGE_ACCOUNT_NAME
BLOB_CONTAINER = _settings.AZURE_AI_SEARCH_BLOB_CONTAINER
CHAT_MODEL = _settings.AZURE_OPENAI_CHAT_MODEL
EMBEDDING_MODEL = _settings.EMBEDDING_MODEL
EMBEDDING_DIMENSIONS = _settings.EMBEDDING_DIMENSIONS
EVAL_MODEL = _settings.AZURE_EVAL_MODEL
COMMON_INDEX_NAME = _settings.COMMON_INDEX_NAME
COMMON_DATASOURCE_NAME = _settings.COMMON_DATASOURCE_NAME
COMMON_SKILLSET_NAME = _settings.COMMON_SKILLSET_NAME
COMMON_INDEXER_NAME = _settings.COMMON_INDEXER_NAME
COMMON_IMAGE_CONTAINER = _settings.COMMON_IMAGE_CONTAINER
