// src/pages/AssetsView.tsx
// Full page view for Assets/Artifacts

import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { 
  Loader2,
  Search,
  X,
  ArrowRight,
  Library
} from "lucide-react";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { PageHeader } from "@/components/layout/PageHeader";
import { cn, getCourseName } from "@/lib/utils";
import { AssetCard } from "@/components/assets/AssetCard";
import { chatApi } from "@/lib/chatApi";
import type { Asset, AssetCategory } from "@/lib/types";
import { useCurrentUserId } from "@/lib/userStore";
import { useChatStore } from "@/lib/chatStore";
import { toast } from "sonner";

const categoryFilters: { key: AssetCategory; label: string }[] = [
  { key: "all", label: "All" },
  { key: "document", label: "Documents" },
  { key: "quiz", label: "Quizzes" },
  { key: "flashcard", label: "Flashcards" },
  { key: "challenge", label: "Challenges" },
];

export function AssetsView() {
  const navigate = useNavigate();
  const userId = useCurrentUserId();
  const [activeCategory, setActiveCategory] = useState<AssetCategory>("all");
  const [assets, setAssets] = useState<Asset[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [hasAnyAssetsAtAll, setHasAnyAssetsAtAll] = useState(true);

  // Fetch total asset count once to know if user has any assets at all
  useEffect(() => {
    async function checkAnyAssets() {
      if (!userId) return;
      try {
        const result = await chatApi.listAssets(userId, { limit: 1 });
        setHasAnyAssetsAtAll(result.assets.length > 0);
      } catch {
        setHasAnyAssetsAtAll(false);
      }
    }
    checkAnyAssets();
  }, [userId]);

  // Fetch user's assets for the active category
  useEffect(() => {
    async function fetchAssets() {
      if (!userId) return;
      
      setIsLoading(true);
      try {
        const result = await chatApi.listAssets(userId, {
          category: activeCategory === "all" ? undefined : activeCategory,
          limit: 50,
        });
        setAssets(result.assets);
        // Update global flag when fetching all
        if (activeCategory === "all") {
          setHasAnyAssetsAtAll(result.assets.length > 0);
        }
      } catch (error) {
        console.error("Failed to fetch assets:", error);
        setAssets([]);
      } finally {
        setIsLoading(false);
      }
    }
    
    fetchAssets();
  }, [userId, activeCategory]);

  // Filter assets by search query
  const filteredAssets = assets.filter((asset) => {
    if (!searchQuery) return true;
    const query = searchQuery.toLowerCase();
    return (
      asset.title.toLowerCase().includes(query) ||
      asset.description?.toLowerCase().includes(query) ||
      asset.tags?.some((t) => t.toLowerCase().includes(query))
    );
  });

  const handleViewAsset = (asset: Asset) => {
    // If the asset has a threadId, navigate to the specific chat where it was created
    if (asset.threadId) {
      // Try to get courseName from: 1) asset tags, 2) thread context, 3) thread agentId
      let courseName = "";
      
      // Check tags for course:name pattern
      const courseTag = asset.tags?.find((t) => t.startsWith("course:"));
      if (courseTag) {
        courseName = courseTag.replace("course:", "");
      }
      
      // Fallback: look up thread in chatStore for courseSlug or agentName
      if (!courseName) {
        const threads = useChatStore.getState().threads;
        const thread = threads[asset.threadId];
        if (thread?.context?.courseSlug) {
          courseName = thread.context.courseSlug;
        } else if (thread?.context?.agentName) {
          courseName = getCourseName(thread.context.agentName);
        }
      }
      
      // Fallback: derive courseName from asset description (e.g. "generated by course-X")
      if (!courseName && asset.description) {
        const match = asset.description.match(/generated by\s+(course-\S+|.+)/i);
        if (match?.[1]) {
          courseName = getCourseName(match[1]);
        }
      }
      
      if (courseName) {
        // Set the active thread before navigating so ChatView loads the right thread
        useChatStore.getState().setActiveThread(asset.threadId);
        navigate(`/chat/${encodeURIComponent(courseName)}/${asset.threadId}`, {
          state: { openAsset: { id: asset.id, title: asset.title, content: asset.content } },
        });
        return;
      }
    }
    
    // Fallback: show toast for assets without navigation info
    toast.info(`Viewing: ${asset.title}`);
  };

  const handleDeleteAsset = async (asset: Asset) => {
    if (!userId) return;
    try {
      await chatApi.deleteAsset(asset.id, userId);
      setAssets((prev) => prev.filter((a) => a.id !== asset.id));
      toast.success("Asset deleted");
    } catch (error) {
      toast.error("Failed to delete asset");
    }
  };

  const handleShareAsset = async (asset: Asset) => {
    if (!userId) return;
    try {
      const updated = await chatApi.updateAsset(asset.id, userId, {
        isPublic: !asset.isPublic,
      });
      setAssets((prev) => prev.map((a) => (a.id === asset.id ? updated : a)));
      toast.success(updated.isPublic ? "Asset is now public" : "Asset is now private");
    } catch (error) {
      toast.error("Failed to update asset");
    }
  };

  const [isScrolled, setIsScrolled] = useState(false);

  const hasAssets = assets.length > 0;

  // Category-specific empty messages
  const categoryEmptyMessages: Record<string, string> = {
    quiz: "No quizzes yet",
    flashcard: "No flashcards yet",
    document: "No documents yet",
    challenge: "No challenges yet",
  };
  const categoryEmptyDescriptions: Record<string, string> = {
    quiz: "Generate quizzes from your chat sessions to test your knowledge.",
    flashcard: "Create flashcards during your learning sessions for quick revision.",
    document: "Documents generated from your conversations will appear here.",
    challenge: "Challenges created during your learning sessions will appear here.",
  };

  return (
    <div 
      className="h-full overflow-y-auto bg-neutral-900 select-none"
      onScroll={(e) => setIsScrolled(e.currentTarget.scrollTop > 10)}
    >
      {/* Header */}
      <PageHeader title="Assets" showBorder={isScrolled} />

      {/* Title Section - only when user has any assets at all */}
      {hasAnyAssetsAtAll && (
        <div className="relative mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 pb-4 pt-16">
          <div className="text-center mb-2">
            <h1 className="text-6xl font-bold text-white mb-4">
              Your Assets
            </h1>
            <p className="text-neutral-400 text-lg max-w-2xl mx-auto leading-relaxed">
              Documents, quizzes, flashcards, and code generated from your learning sessions.
            </p>
          </div>
        </div>
      )}

      {/* Search Bar - only when user has any assets at all */}
      {!isLoading && hasAnyAssetsAtAll && (
        <div className="sticky top-[56px] z-20 pt-4 pb-0.3 bg-neutral-900">
          <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
            <div className="relative w-full">
              <Search className="absolute left-5 top-1/2 transform -translate-y-1/2 h-5 w-5 text-neutral-400" />
              <Input
                type="text"
                placeholder="Search assets..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-14 pr-5 py-7 text-[18px] bg-neutral-800/80 border border-neutral-700/60 rounded-xl text-white placeholder:text-[18px] placeholder:text-neutral-500 focus:border-neutral-600 focus:bg-neutral-800 focus:outline-none focus:ring-0 focus-visible:ring-0 focus-visible:outline-none hover:border-neutral-600 transition-colors shadow-md shadow-black/20"
              />
              {searchQuery && (
                <button
                  type="button"
                  onClick={() => setSearchQuery("")}
                  className="absolute right-5 top-1/2 transform -translate-y-1/2 text-neutral-400 hover:text-white"
                >
                  <X className="h-4 w-4" />
                </button>
              )}
            </div>
          </div>
        </div>
      )}

      <div className="relative mx-auto max-w-4xl px-4 sm:px-6 lg:px-8 pb-8 pt-8">
        {/* Category Filters - only when user has any assets at all */}
        {hasAnyAssetsAtAll && (
          <nav className="flex items-center justify-center gap-10 mb-8">
            {categoryFilters.map(({ key, label }) => (
              <button
                key={key}
                type="button"
                onClick={() => setActiveCategory(key)}
                className={cn(
                  "pb-3 text-sm font-medium transition-colors outline-none relative",
                  activeCategory === key
                    ? "text-white"
                    : "text-neutral-500 hover:text-neutral-300"
                )}
              >
                {label}
                {activeCategory === key && (
                  <span className="absolute bottom-0 left-0 right-0 h-0.5 bg-white rounded-full" />
                )}
              </button>
            ))}
          </nav>
        )}

        {/* Assets Grid */}
        {isLoading ? (
          <div className="flex flex-col items-center justify-center min-h-[60vh]">
            <div className="w-12 h-12 rounded-full border-4 border-neutral-600/30 border-t-neutral-400 animate-spin mb-6" />
            <p className="text-neutral-400 text-lg">Loading...</p>
          </div>
        ) : !hasAnyAssetsAtAll ? (
          /* Global Empty State - no assets at all */
          <div className="flex flex-col items-center justify-center min-h-[calc(100vh-120px)] -mt-8 text-center max-w-lg mx-auto">
            <h1 className="text-4xl font-semibold tracking-tight text-white">
              Your Assets
            </h1>
            <p className="mt-4 text-[15px] text-neutral-400 leading-relaxed">
              Assets created from your chat sessions will appear here. Start a conversation with a teaching assistant to generate quizzes, flashcards, and more!
            </p>
            <div className="flex items-center justify-center gap-3 mt-8">
              <Button
                onClick={() => navigate("/library")}
                className="px-5 h-10 bg-white hover:bg-neutral-200 text-neutral-900 font-medium text-sm rounded-lg transition-colors duration-200"
              >
                <Library className="h-4 w-4 mr-2" />
                Explore Agents
              </Button>
              <Button
                onClick={() => navigate("/learn#assets")}
                variant="outline"
                className="px-5 h-10 border-neutral-700 hover:bg-neutral-800 text-neutral-300 hover:text-white font-medium text-sm rounded-lg transition-colors duration-200"
              >
                <ArrowRight className="h-4 w-4 mr-2" />
                Learn More
              </Button>
            </div>
          </div>
        ) : !hasAssets && activeCategory !== "all" ? (
          /* Category-specific empty state */
          <div className="flex flex-col items-center justify-center py-20 px-4">
            <h3 className="text-xl font-semibold text-white mb-2">
              {categoryEmptyMessages[activeCategory] || "No assets yet"}
            </h3>
            <p className="text-neutral-400 text-center max-w-md">
              {categoryEmptyDescriptions[activeCategory] || "Assets in this category will appear here."}
            </p>
          </div>
        ) : filteredAssets.length === 0 ? (
          <div className="flex flex-col items-center justify-center py-20 px-4">
            <h3 className="text-xl font-semibold text-white mb-2">
              No matching assets
            </h3>
            <p className="text-neutral-400 text-center max-w-md mb-6">
              No assets found matching "{searchQuery}"
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">
            {filteredAssets.map((asset) => (
              <AssetCard
                key={asset.id}
                asset={asset}
                onView={handleViewAsset}
                onDelete={handleDeleteAsset}
                onShare={handleShareAsset}
                showActions={true}
              />
            ))}
          </div>
        )}

      </div>
    </div>
  );
}
