import { Plus, Trash2 } from "lucide-react";
import type { CircuitComponent, CircuitSpec } from "@/lib/circuit";
import { CONTROLLER_KINDS, DEVICE_EVENT_ACTIONS, DEVICE_FIELDS, DEVICE_PARAMETERS, FAULT_KINDS, FAULT_TARGETS, OPERATED_KINDS, PLC_TERMINALS, TERMINAL_LABELS, type CircuitEvent, type CircuitFault, type PLCRung } from "@/lib/circuitDevices";

const FIELD = "h-8 min-w-0 w-full rounded-md border border-neutral-600 bg-neutral-950 px-2 text-xs text-neutral-100 disabled:opacity-60";
const ICON = "inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md text-neutral-300 hover:bg-neutral-700 disabled:opacity-40";
const LABEL = "min-w-0 space-y-1 text-xs text-neutral-400";

export function CircuitDeviceInspector({ circuit, part, patch, locked }: { circuit: CircuitSpec; part: CircuitComponent; patch: (patch: Partial<CircuitComponent>) => void; locked: boolean }) {
  const controllers = circuit.components.filter(component => component.id !== part.id && CONTROLLER_KINDS.includes(component.kind));
  const fields = DEVICE_FIELDS[part.kind] ?? [];
  const linked = ["contact_no", "contact_nc", "contactor"].includes(part.kind);
  const editRung = (index: number, next: Partial<PLCRung>) => patch({ rungs: (part.rungs ?? []).map((rung, position) => position === index ? { ...rung, ...next } : rung) });
  return <fieldset disabled={locked} className="space-y-3">
    {!!Object.keys(part.terminals ?? {}).length && <div className="grid grid-cols-2 gap-2">{Object.entries(part.terminals ?? {}).map(([terminal, node]) => <label key={terminal} className={LABEL}>{terminal}<input aria-label={`${part.id} ${terminal} node`} className={FIELD} value={node} maxLength={16} pattern="(0|[A-Za-z][A-Za-z0-9_]{0,15})" onChange={event => patch({ terminals: { ...part.terminals, [terminal]: event.target.value } })} /></label>)}</div>}
    {(linked || ["contactor_coil", "timer_relay"].includes(part.kind)) && <div className="grid grid-cols-2 gap-2">
      {linked && <label className={LABEL}>Controller<select className={FIELD} aria-label={`${part.id} controller`} value={part.link ?? ""} onChange={event => patch({ link: event.target.value || null })}><option value="">Select controller</option>{controllers.map(controller => <option key={controller.id} value={controller.id}>{controller.id}</option>)}</select></label>}
      <label className={LABEL}>Mechanical interlock<select className={FIELD} aria-label={`${part.id} interlock`} value={part.interlock ?? ""} onChange={event => patch({ interlock: event.target.value || null })}><option value="">None</option>{controllers.map(controller => <option key={controller.id} value={controller.id}>{controller.id}</option>)}</select></label>
    </div>}
    {OPERATED_KINDS.includes(part.kind) && part.kind !== "switch" && <label className="flex items-center gap-2 text-xs text-neutral-300"><input type="checkbox" aria-label={`${part.id} operated`} checked={part.closed ?? true} onChange={event => patch({ closed: event.target.checked })} />{["pushbutton_no", "pushbutton_nc", "emergency_stop"].includes(part.kind) ? "Pressed initially" : "Active initially"}</label>}
    {part.kind === "three_phase_source" && <label className={`${LABEL} block`}>Frequency (Hz)<input aria-label={`${part.id} frequency`} className={FIELD} type="number" min={0.1} max={100000} value={part.frequency_hz ?? 50} onChange={event => patch({ frequency_hz: event.target.valueAsNumber })} /></label>}
    {!!fields.length && <details className="border-t border-neutral-700 pt-2"><summary className="cursor-pointer text-xs text-neutral-300">Model parameters</summary><div className="mt-2 grid grid-cols-2 gap-2">{fields.map(key => {
      const field = DEVICE_PARAMETERS[key];
      const value = part.parameters?.[key] ?? field.initial;
      const update = (next: number | string) => patch({ parameters: { ...part.parameters, [key]: next } });
      return <label key={key} className={LABEL}>{field.label}{field.options ? <select aria-label={`${part.id} ${field.label}`} className={FIELD} value={value} onChange={event => update(event.target.value)}>{field.options.map(option => <option key={option} value={option}>{option.replaceAll("_", " ")}</option>)}</select> : <input aria-label={`${part.id} ${field.label}`} className={FIELD} type="number" min={field.min} max={field.max} step={field.integer ? 1 : "any"} value={value} onChange={event => update(event.target.valueAsNumber)} />}</label>;
    })}</div></details>}
    {part.kind === "plc" && <section aria-label="PLC logic" className="border-t border-neutral-700 pt-2">
      <div className="flex items-center justify-between"><h4 className="text-xs text-neutral-300">Logic rungs</h4><button type="button" className={ICON} title="Add rung" aria-label="Add PLC rung" disabled={(part.rungs?.length ?? 0) >= 8} onClick={() => patch({ rungs: [...(part.rungs ?? []), { output: "OUT1", operation: "and", inputs: [{ terminal: "IN1" }], preset: 1 }] })}><Plus className="h-4 w-4" /></button></div>
      {(part.rungs ?? []).map((rung, index) => <div className="space-y-2 border-t border-neutral-800 py-2" key={index} aria-label={`PLC rung ${index + 1}`}>
        <div className="grid grid-cols-[1fr_1fr_2rem] gap-2"><label className={LABEL}>Operation<select aria-label={`Rung ${index + 1} operation`} className={FIELD} value={rung.operation} onChange={event => editRung(index, { operation: event.target.value as PLCRung["operation"] })}>{["and", "or", "set", "reset", "ton", "ctu"].map(operation => <option key={operation} value={operation}>{operation.toUpperCase()}</option>)}</select></label><label className={LABEL}>Output<select aria-label={`Rung ${index + 1} output`} className={FIELD} value={rung.output} onChange={event => editRung(index, { output: event.target.value as PLCRung["output"] })}>{PLC_TERMINALS.filter(terminal => terminal.startsWith("OUT")).map(terminal => <option key={terminal} value={terminal}>{terminal}</option>)}</select></label><button type="button" className={`${ICON} self-end`} aria-label={`Remove rung ${index + 1}`} title="Remove rung" onClick={() => patch({ rungs: part.rungs?.filter((_, position) => position !== index) })}><Trash2 className="h-3.5 w-3.5" /></button></div>
        {rung.inputs.map((input, inputIndex) => <div key={inputIndex} className="flex items-center gap-2"><select aria-label={`Rung ${index + 1} input ${inputIndex + 1}`} className={FIELD} value={input.terminal} onChange={event => editRung(index, { inputs: rung.inputs.map((item, position) => position === inputIndex ? { ...item, terminal: event.target.value as typeof input.terminal } : item) })}>{PLC_TERMINALS.map(terminal => <option key={terminal} value={terminal}>{terminal}</option>)}</select><label className="flex shrink-0 items-center gap-1 text-xs"><input type="checkbox" aria-label={`Rung ${index + 1} input ${inputIndex + 1} NC`} checked={!!input.normally_closed} onChange={event => editRung(index, { inputs: rung.inputs.map((item, position) => position === inputIndex ? { ...item, normally_closed: event.target.checked } : item) })} />NC</label><button type="button" className={ICON} disabled={rung.inputs.length <= 1} aria-label={`Remove rung ${index + 1} input ${inputIndex + 1}`} title="Remove input" onClick={() => editRung(index, { inputs: rung.inputs.filter((_, position) => position !== inputIndex) })}><Trash2 className="h-3.5 w-3.5" /></button></div>)}
        <div className="flex items-center gap-2"><button type="button" className={ICON} aria-label={`Add rung ${index + 1} input`} title="Add input" disabled={rung.inputs.length >= 8} onClick={() => editRung(index, { inputs: [...rung.inputs, { terminal: "IN1" }] })}><Plus className="h-3.5 w-3.5" /></button>{["ton", "ctu"].includes(rung.operation) && <label className={LABEL}>{rung.operation === "ton" ? "Delay (s)" : "Count"}<input aria-label={`Rung ${index + 1} preset`} className={FIELD} type="number" min={0.001} max={1000} value={rung.preset ?? 1} onChange={event => editRung(index, { preset: event.target.valueAsNumber })} /></label>}</div>
      </div>)}
    </section>}
  </fieldset>;
}

export function CircuitTimeline({ circuit, change, locked }: { circuit: CircuitSpec; change: (circuit: CircuitSpec) => void; locked: boolean }) {
  const events = circuit.events ?? [];
  const faults = circuit.faults ?? [];
  const operated = circuit.components.filter(part => DEVICE_EVENT_ACTIONS[part.kind]);
  const updateEvent = (index: number, patch: Partial<CircuitEvent>) => change({ ...circuit, format_version: 2, events: events.map((event, position) => position === index ? { ...event, ...patch } : event) });
  const updateFault = (index: number, patch: Partial<CircuitFault>) => change({ ...circuit, format_version: 2, faults: faults.map((fault, position) => position === index ? { ...fault, ...patch } : fault) });
  return <fieldset disabled={locked} className="mt-3 space-y-3 border-t border-neutral-700 pt-2">
    <details><summary className="cursor-pointer text-xs text-neutral-300">Timeline ({events.length})</summary><button type="button" className="my-2 flex h-8 items-center gap-2 text-xs text-cyan-200 disabled:opacity-40" disabled={events.length >= 64 || !operated.length} onClick={() => change({ ...circuit, format_version: 2, analysis: { ...circuit.analysis, mode: "transient" }, events: [...events, { component_id: operated[0].id, time_seconds: 0, action: DEVICE_EVENT_ACTIONS[operated[0].kind][0] }] })}><Plus className="h-3.5 w-3.5" />Add event</button>
      {events.map((event, index) => <div key={index} className="mb-3 grid grid-cols-2 gap-2 border-b border-neutral-800 pb-2" aria-label={`Circuit event ${index + 1}`}><label className={LABEL}>Device<select className={FIELD} aria-label={`Event ${index + 1} device`} value={event.component_id} onChange={changeEvent => { const target = operated.find(part => part.id === changeEvent.target.value)!; updateEvent(index, { component_id: target.id, action: DEVICE_EVENT_ACTIONS[target.kind][0] }); }}>{operated.map(part => <option key={part.id} value={part.id}>{part.id}</option>)}</select></label><label className={LABEL}>Time (s)<input type="number" className={FIELD} min={0} max={circuit.analysis.duration_seconds ?? 0.05} step="any" aria-label={`Event ${index + 1} time`} value={event.time_seconds} onChange={changeEvent => updateEvent(index, { time_seconds: changeEvent.target.valueAsNumber })} /></label><label className={LABEL}>Action<select className={FIELD} aria-label={`Event ${index + 1} action`} value={event.action} onChange={changeEvent => updateEvent(index, { action: changeEvent.target.value as CircuitEvent["action"] })}>{(DEVICE_EVENT_ACTIONS[circuit.components.find(part => part.id === event.component_id)?.kind ?? ""] ?? []).map(action => <option key={action} value={action}>{action.replaceAll("_", " ")}</option>)}</select></label><div className="flex items-end gap-2">{event.action === "analog" && <input type="number" className={FIELD} aria-label={`Event ${index + 1} voltage`} min={0} max={24} step="any" value={event.value ?? 0} onChange={changeEvent => updateEvent(index, { value: changeEvent.target.valueAsNumber })} />}<button type="button" className={ICON} aria-label={`Remove event ${index + 1}`} title="Remove event" onClick={() => change({ ...circuit, events: events.filter((_, position) => position !== index) })}><Trash2 className="h-3.5 w-3.5" /></button></div></div>)}
    </details>
    <details><summary className="cursor-pointer text-xs text-neutral-300">Injected faults ({faults.length})</summary><button type="button" className="my-2 flex h-8 items-center gap-2 text-xs text-amber-200 disabled:opacity-40" disabled={faults.length >= 16} onClick={() => change({ ...circuit, format_version: 2, faults: [...faults, { component_id: circuit.components[0].id, kind: "open_wire", terminal: "positive" }] })}><Plus className="h-3.5 w-3.5" />Inject fault</button>
      {faults.map((fault, index) => {
        const target = circuit.components.find(part => part.id === fault.component_id) ?? circuit.components[0];
        return <div key={index} className="mb-3 grid grid-cols-2 gap-2 border-b border-neutral-800 pb-2" aria-label={`Circuit fault ${index + 1}`}>
          <label className={LABEL}>Device<select className={FIELD} aria-label={`Fault ${index + 1} device`} value={fault.component_id} onChange={event => updateFault(index, { component_id: event.target.value, kind: "open_wire", terminal: "positive" })}>{circuit.components.map(part => <option key={part.id} value={part.id}>{part.id}</option>)}</select></label>
          <label className={LABEL}>Fault<select className={FIELD} aria-label={`Fault ${index + 1} type`} value={fault.kind} onChange={event => updateFault(index, { kind: event.target.value as CircuitFault["kind"] })}>{Object.entries(FAULT_KINDS).filter(([kind]) => !FAULT_TARGETS[kind] || FAULT_TARGETS[kind].includes(target.kind)).map(([kind, label]) => <option key={kind} value={kind}>{label}</option>)}</select></label>
          <label className={LABEL}>Terminal<select className={FIELD} aria-label={`Fault ${index + 1} terminal`} value={fault.terminal} onChange={event => updateFault(index, { terminal: event.target.value })}>{["positive", "negative", ...Object.keys(target.terminals ?? {})].map(terminal => <option key={terminal} value={terminal}>{terminal === "positive" ? TERMINAL_LABELS[target.kind]?.[0] ?? "+" : terminal === "negative" ? TERMINAL_LABELS[target.kind]?.[1] ?? "-" : terminal}</option>)}</select></label>
          <label className={LABEL}>Severity<input aria-label={`Fault ${index + 1} severity`} type="range" className="h-8 w-full accent-amber-400" min={0} max={1} step={0.01} value={fault.severity ?? 0.8} onChange={event => updateFault(index, { severity: event.target.valueAsNumber })} /></label>
          {["burnt_contact", "loose_neutral", "insulation_leakage", "earth_fault"].includes(fault.kind) && <label className={LABEL}>Resistance (ohm)<input aria-label={`Fault ${index + 1} resistance`} className={FIELD} type="number" min={0.001} max={1e12} step="any" value={fault.resistance_ohm ?? 1000} onChange={event => updateFault(index, { resistance_ohm: event.target.valueAsNumber })} /></label>}
          {circuit.analysis.mode === "transient" && <><label className={LABEL}>Start (s)<input className={FIELD} aria-label={`Fault ${index + 1} start`} type="number" min={0} max={circuit.analysis.duration_seconds ?? 0.05} step="any" value={fault.start_seconds ?? 0} onChange={event => updateFault(index, { start_seconds: event.target.valueAsNumber })} /></label><label className={LABEL}>End (s)<input className={FIELD} aria-label={`Fault ${index + 1} end`} type="number" min={0} max={circuit.analysis.duration_seconds ?? 0.05} step="any" value={fault.end_seconds ?? ""} onChange={event => updateFault(index, { end_seconds: event.target.value === "" ? null : event.target.valueAsNumber })} /></label></>}
          <button type="button" className={`${ICON} self-end`} aria-label={`Remove fault ${index + 1}`} title="Remove fault" onClick={() => change({ ...circuit, faults: faults.filter((_, position) => position !== index) })}><Trash2 className="h-3.5 w-3.5" /></button>
        </div>;
      })}
    </details>
    <details><summary className="cursor-pointer text-xs text-neutral-300">Conductor roles</summary><div className="mt-2 grid grid-cols-2 gap-2">{[...new Set(circuit.components.flatMap(part => [part.positive, part.negative, ...Object.values(part.terminals ?? {})]))].map(node => <label key={node} className={LABEL}>{node}<select aria-label={`Node ${node} role`} className={FIELD} value={circuit.node_roles?.[node] ?? ""} onChange={event => { const roles = { ...circuit.node_roles }; if (event.target.value) roles[node] = event.target.value as NonNullable<CircuitSpec["node_roles"]>[string]; else delete roles[node]; change({ ...circuit, format_version: 2, node_roles: roles }); }}><option value="">Unassigned</option>{["L1", "L2", "L3", "N", "PE", "DC+", "DC-"].map(role => <option key={role} value={role}>{role}</option>)}</select></label>)}</div></details>
  </fieldset>;
}