// src/components/assets/AssetCard.tsx
// Card component for displaying assets/artifacts — NotebookLM-inspired flat layout

import { 
  FileCode, 
  FileText, 
  HelpCircle, 
  BookOpen,
  Code,
  GitBranch,
  Sparkles,
  Zap
} from "lucide-react";
import type { Asset } from "@/lib/types";
import { cn, getCourseName } from "@/lib/utils";

interface AssetCardProps {
  asset: Asset;
  onView?: (asset: Asset) => void;
  onDelete?: (asset: Asset) => void;
  onShare?: (asset: Asset) => void;
  showActions?: boolean;
}

// Category icon mapping
const categoryIcons: Record<string, React.ElementType> = {
  document: FileText,
  quiz: HelpCircle,
  flashcard: BookOpen,
  challenge: Zap,
  diagram: GitBranch,
  summary: FileText,
  code: Code,
  visualization: Sparkles,
  other: FileCode,
};

// Category accent colors (icon bg + text)
const categoryAccents: Record<string, { icon: string; badge: string }> = {
  quiz:          { icon: "bg-purple-500/15 text-purple-400", badge: "text-purple-400" },
  flashcard:     { icon: "bg-blue-500/15 text-blue-400",     badge: "text-blue-400" },
  document:      { icon: "bg-cyan-500/15 text-cyan-400", badge: "text-cyan-400" },
  challenge:     { icon: "bg-amber-500/15 text-amber-400", badge: "text-amber-400" },
  diagram:       { icon: "bg-green-500/15 text-green-400",   badge: "text-green-400" },
  summary:       { icon: "bg-yellow-500/15 text-yellow-400", badge: "text-yellow-400" },
  code:          { icon: "bg-orange-500/15 text-orange-400", badge: "text-orange-400" },
  visualization: { icon: "bg-pink-500/15 text-pink-400",     badge: "text-pink-400" },
  other:         { icon: "bg-neutral-500/15 text-neutral-400", badge: "text-neutral-400" },
};

// Friendly category labels
const categoryLabels: Record<string, string> = {
  quiz: "Quiz",
  flashcard: "Flashcards",
  document: "Document",
  challenge: "Challenge",
  diagram: "Diagram",
  summary: "Summary",
  code: "Code",
  visualization: "Visualization",
  other: "Other",
};

// Extract item count from description (e.g. "Quiz with 5 questions", "6 flashcards")
function getItemCount(asset: Asset): string | null {
  if (!asset.description) return null;
  const d = asset.description;
  // "Quiz with 5 questions"
  const qMatch = d.match(/(\d+)\s+question/i);
  if (qMatch) return `${qMatch[1]} questions`;
  // "6 flashcards"
  const fMatch = d.match(/(\d+)\s+flashcard/i);
  if (fMatch) return `${fMatch[1]} cards`;
  return null;
}

// Extract course name from asset tags or description
function getAssetCourseName(asset: Asset): string | null {
  // 1) From tags: "course:Machine Learning"
  const courseTag = asset.tags?.find((t) => t.startsWith("course:"));
  if (courseTag) return courseTag.replace("course:", "");
  // 2) From description: "generated by course-Machine-Learning"
  const match = asset.description?.match(/generated by\s+(\S+)/i);
  if (match?.[1]) return getCourseName(match[1]);
  return null;
}

export function AssetCard({ 
  asset, 
  onView, 
  onDelete, 
  onShare,
  showActions = true 
}: AssetCardProps) {
  const Icon = categoryIcons[asset.category] || FileCode;
  const accent = categoryAccents[asset.category] || categoryAccents.other;
  const label = categoryLabels[asset.category] || "Other";
  const itemCount = getItemCount(asset);
  const courseName = getAssetCourseName(asset);
  
  const formatDate = (date: string) => {
    const d = new Date(date);
    const now = new Date();
    const diff = now.getTime() - d.getTime();
    const days = Math.floor(diff / (1000 * 60 * 60 * 24));
    
    if (days === 0) {
      // Today — show time like "2:34 PM"
      return d.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true });
    }
    if (days === 1) return "Yesterday";
    if (days < 7) return `${days} days ago`;
    if (days < 30) return `${Math.floor(days / 7)} weeks ago`;
    if (days < 365) return d.toLocaleDateString("en-US", { day: "numeric", month: "short" });
    return d.toLocaleDateString("en-US", { day: "numeric", month: "short", year: "numeric" });
  };

  return (
    <div
      className="group relative flex flex-col justify-between rounded-2xl bg-neutral-800/60 border border-neutral-700/40 hover:border-neutral-600/70 hover:bg-neutral-800/80 transition-all duration-200 cursor-pointer p-4 min-h-[140px]"
      onClick={() => onView?.(asset)}
    >
      {/* Top row — category label */}
      <div className="flex items-center">
        <span className={cn("text-xs font-medium", accent.badge)}>
          {label}
        </span>
      </div>

      {/* Title */}
      <h3 className="text-[17px] font-semibold text-white leading-snug mt-3 line-clamp-2">
        {asset.title}
      </h3>

      {/* Bottom row — date · count · course */}
      <div className="flex items-center mt-3 min-w-0">
        <div className="flex items-center gap-1.5 text-[11px] text-neutral-500 min-w-0">
          <span className="shrink-0 whitespace-nowrap">{formatDate(asset.createdAt)}</span>
          {itemCount && (
            <>
              <span className="shrink-0">·</span>
              <span className="shrink-0 whitespace-nowrap">{itemCount}</span>
            </>
          )}
          {courseName && (
            <>
              <span className="shrink-0">·</span>
              <span className="truncate min-w-0">{courseName}</span>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
